"use client";

import { useState, useMemo } from "react";
import { 
  Lock, Globe, ShieldCheck, Download, Code, Settings,
  Shield, Terminal, Bot, Zap, BookOpen,
  HelpCircle, Cpu, 
  Activity, SearchCode
} from "lucide-react";
import { generateSoftwareApplicationSchema } from "@/lib/structuredData";

export default function RobotsTxtBuilderPage() {
  const [sitemap, setSitemap] = useState("https://yourdomain.com/sitemap.xml");
  const [allowGoogle, setAllowGoogle] = useState(true);
  const [allowBing, setAllowBing] = useState(true);
  const [allowDuckDuckGo, setAllowDuckDuckGo] = useState(true);
  const [allowAI, setAllowAI] = useState(false);
  const [disallowAdmin, setDisallowAdmin] = useState(true);
  const [disallowCgi, setDisallowCgi] = useState(true);
  const [disallowTemp, setDisallowTemp] = useState(true);
  const [delay, setDelay] = useState(0);
  const [copied, setCopied] = useState(false);

  const robotsContent = useMemo(() => {
    let robots = "# robots.txt generated by SamToolbox Crawler Shield\n";
    robots += `# Optimization Date: ${new Date().toLocaleDateString()}\n\n`;

    if (delay > 0) {
      robots += `User-agent: *\nCrawl-delay: ${delay}\n\n`;
    }

    if (!allowAI) {
      robots += "# Block AI Intelligence Scrapers\nUser-agent: GPTBot\nDisallow: /\nUser-agent: Claude-Web\nDisallow: /\nUser-agent: CCBot\nDisallow: /\nUser-agent: anthropic-ai\nDisallow: /\nUser-agent: OAI-SearchBot\nDisallow: /\n\n";
    }

    if (!allowGoogle) robots += "User-agent: Googlebot\nDisallow: /\n\n";
    if (!allowBing) robots += "User-agent: Bingbot\nDisallow: /\n\n";
    if (!allowDuckDuckGo) robots += "User-agent: DuckDuckBot\nDisallow: /\n\n";

    robots += "User-agent: *\n";
    if (disallowAdmin) robots += "Disallow: /admin/\nDisallow: /login/\nDisallow: /wp-admin/\nDisallow: /dashboard/\n";
    if (disallowCgi) robots += "Disallow: /cgi-bin/\n";
    if (disallowTemp) robots += "Disallow: /tmp/\nDisallow: /cache/\n";
    robots += "Allow: /\n\n";

    if (sitemap) {
      robots += `Sitemap: ${sitemap}\n`;
    }

    return robots.trim();
  }, [sitemap, allowGoogle, allowBing, allowDuckDuckGo, allowAI, disallowAdmin, disallowCgi, disallowTemp, delay]);

  const handleCopy = () => {
    navigator.clipboard.writeText(robotsContent);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const element = document.createElement("a");
    const file = new Blob([robotsContent], {type: 'text/plain'});
    element.href = URL.createObjectURL(file);
    element.download = "robots.txt";
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  const schema = useMemo(() => generateSoftwareApplicationSchema("robots-txt-builder", "Industrial-grade search compliance engine for high-security websites."), []);

  return (
    <div className="min-h-screen bg-[#020617] selection:bg-emerald-500/30 selection:text-emerald-200">
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} />

      {/* ══════════════════════════════════════════
          HERO / HEADER
      ══════════════════════════════════════════ */}
      <section className="pt-24 pb-32 px-6 relative overflow-hidden text-center">
        <div className="absolute inset-0 opacity-[0.03] pointer-events-none" 
             style={{ backgroundImage: "radial-gradient(#ffffff 1px, transparent 1px)", backgroundSize: "40px 40px" }} />
        
        <div className="max-w-4xl mx-auto relative z-10">
          <div className="inline-flex items-center gap-2 px-4 py-2 bg-emerald-500/10 border border-emerald-500/20 rounded-full text-emerald-400 font-black text-[10px] uppercase tracking-[0.4em] mb-10 shadow-2xl">
            <Shield size={14} className="animate-pulse" />
            Crawler Shield v9.1
          </div>
          <h1 className="text-6xl md:text-[7rem] font-black text-white tracking-tighter mb-8 leading-none">
            Robots <span className="text-transparent bg-clip-text bg-gradient-to-r from-emerald-400 to-teal-400 italic">Builder.</span>
          </h1>
          <p className="text-slate-400 text-lg md:text-xl max-w-3xl mx-auto font-medium leading-relaxed">
            Search compliance engineering. 
            <span className="text-slate-200 font-bold block mt-2">Index Sovereignty. AI Scraping Blockade. Industrial SEO Logic.</span>
          </p>
        </div>
      </section>

      {/* ══════════════════════════════════════════
          MAIN UTILITY INTERFACE
      ══════════════════════════════════════════ */}
      <section className="max-w-7xl mx-auto px-6 -mt-16 relative z-20 mb-32">
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-10 items-start">
          
          {/* Workspace */}
          <div className="lg:col-span-8 space-y-8">
            <div className="bg-[#0f172a] rounded-[3.5rem] border border-white/5 shadow-3xl shadow-black overflow-hidden animate-in fade-in slide-in-from-bottom-8 duration-700">
               <div className="bg-white/5 px-10 py-8 border-b border-white/5 flex flex-col sm:flex-row items-center justify-between gap-6">
                  <div className="flex items-center gap-4">
                     <div className="p-3 bg-emerald-500/10 border border-emerald-500/20 rounded-2xl text-emerald-400">
                        <Terminal size={22} />
                     </div>
                     <div>
                        <h3 className="text-lg font-black text-white uppercase tracking-tighter leading-none">Directive Forge</h3>
                        <p className="text-[10px] font-black text-slate-600 uppercase tracking-widest mt-1 italic">Mapping compliance</p>
                     </div>
                  </div>
                  <div className="flex items-center gap-3">
                     <button 
                       onClick={handleCopy}
                       className="px-6 py-3 bg-white/5 hover:bg-white/10 text-white rounded-xl text-[10px] font-black uppercase tracking-widest transition-all border border-white/5 shadow-xl"
                     >
                       <Code size={14} className="mr-2 inline" /> {copied ? "Copied" : "Copy Source"}
                     </button>
                     <button 
                       onClick={handleDownload}
                       className="px-6 py-3 bg-emerald-600 text-white rounded-xl text-[10px] font-black uppercase tracking-widest transition-all shadow-xl"
                     >
                       <Download size={14} className="mr-2 inline" /> Download .txt
                     </button>
                  </div>
               </div>

               <div className="p-10 grid grid-cols-1 md:grid-cols-2 gap-10">
                  {/* Configuration Controls */}
                  <div className="space-y-10">
                     <div className="space-y-4">
                        <label className="text-[10px] font-black text-slate-500 uppercase tracking-widest ml-4">Sitemap Vector</label>
                        <input 
                          type="url"
                          value={sitemap}
                          onChange={e => setSitemap(e.target.value)}
                          className="w-full bg-black/40 border border-white/5 rounded-2xl px-6 py-4 text-white font-bold outline-none focus:border-emerald-500/30 transition-all text-sm"
                          placeholder="https://domain.com/sitemap.xml"
                        />
                     </div>

                     <div className="space-y-6 p-8 bg-white/5 rounded-3xl border border-white/5">
                        <div className="flex items-center gap-3 mb-2">
                           <Globe size={18} className="text-emerald-400" />
                           <span className="text-[10px] font-black text-white uppercase tracking-widest">Search Permissions</span>
                        </div>
                        <div className="space-y-4">
                           {[
                             { id: 'google', label: 'Allow Google', state: allowGoogle, set: setAllowGoogle },
                             { id: 'bing', label: 'Allow Bing', state: allowBing, set: setAllowBing },
                             { id: 'ai', label: 'Allow AI Bots', state: allowAI, set: setAllowAI },
                           ].map(opt => (
                             <button
                               key={opt.id}
                               onClick={() => opt.set(!opt.state)}
                               className={`w-full p-4 rounded-xl border flex items-center justify-between transition-all ${opt.state ? "bg-emerald-600/10 border-emerald-500/20 text-white" : "bg-white/5 border-white/5 text-slate-500"}`}
                             >
                                <span className="text-[10px] font-black uppercase tracking-widest">{opt.label}</span>
                                <div className={`w-4 h-4 rounded-full border-2 transition-all ${opt.state ? "bg-emerald-500 border-emerald-400" : "border-slate-700"}`} />
                             </button>
                           ))}
                        </div>
                     </div>

                     <div className="space-y-6 p-8 bg-white/5 rounded-3xl border border-white/5">
                        <div className="flex items-center gap-3 mb-2">
                           <Lock size={18} className="text-emerald-400" />
                           <span className="text-[10px] font-black text-white uppercase tracking-widest">Security Blockade</span>
                        </div>
                        <div className="space-y-4">
                           {[
                             { id: 'admin', label: 'Block Admin Pages', state: disallowAdmin, set: setDisallowAdmin },
                             { id: 'cgi', label: 'Block CGI Bins', state: disallowCgi, set: setDisallowCgi },
                             { id: 'tmp', label: 'Block Temp Files', state: disallowTemp, set: setDisallowTemp },
                           ].map(opt => (
                             <button
                               key={opt.id}
                               onClick={() => opt.set(!opt.state)}
                               className={`w-full p-4 rounded-xl border flex items-center justify-between transition-all ${opt.state ? "bg-emerald-600/10 border-emerald-500/20 text-white" : "bg-white/5 border-white/5 text-slate-500"}`}
                             >
                                <span className="text-[10px] font-black uppercase tracking-widest">{opt.label}</span>
                                <div className={`w-4 h-4 rounded-full border-2 transition-all ${opt.state ? "bg-emerald-500 border-emerald-400" : "border-slate-700"}`} />
                             </button>
                           ))}
                        </div>
                     </div>
                  </div>

                  {/* Preview Code */}
                  <div className="relative group">
                     <div className="absolute inset-0 bg-emerald-500/5 rounded-[2.5rem] blur-2xl opacity-0 group-hover:opacity-100 transition-opacity" />
                     <div className="relative bg-black/60 border border-white/5 rounded-[2.5rem] p-10 h-full font-mono text-sm leading-relaxed text-emerald-400/90 overflow-auto custom-scrollbar">
                        <div className="flex items-center justify-between mb-8 border-b border-emerald-500/10 pb-4">
                           <span className="text-[10px] font-black uppercase tracking-[0.4em] text-emerald-500">Live Preview</span>
                           <Bot size={16} />
                        </div>
                        <pre className="whitespace-pre-wrap">{robotsContent}</pre>
                     </div>
                  </div>
               </div>
            </div>
          </div>

          {/* Action Sidebar */}
          <div className="lg:col-span-4 space-y-8">
            <div className="bg-[#0f172a] p-10 rounded-[3.5rem] border border-white/5 shadow-3xl shadow-black relative overflow-hidden group">
               <div className="absolute top-0 right-0 w-32 h-32 bg-emerald-600/5 rounded-full blur-3xl" />
               <div className="flex items-center gap-4 mb-8">
                  <div className="p-3 bg-emerald-500/10 border border-emerald-500/20 rounded-2xl text-emerald-400">
                    <SearchCode size={24} />
                  </div>
                  <h3 className="text-xl font-black text-white uppercase tracking-tighter">Compliance</h3>
               </div>
               <div className="space-y-6">
                  <div className="flex items-center justify-between text-sm">
                     <span className="text-slate-500 font-bold">Standard</span>
                     <span className="text-white font-black uppercase tracking-widest text-[10px]">RFC 9309</span>
                  </div>
                  <div className="flex items-center justify-between text-sm">
                     <span className="text-slate-500 font-bold">Bot Protection</span>
                     <span className="text-white font-black uppercase tracking-widest text-[10px]">Multi-Layer</span>
                  </div>
                  <div className="flex items-center gap-3 text-[9px] font-black text-emerald-500 uppercase tracking-[0.4em] pt-4 border-t border-white/5">
                     <div className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse" />
                     Shield Active
                  </div>
               </div>
            </div>

            <div className="bg-gradient-to-br from-emerald-600 to-teal-700 p-10 rounded-[3.5rem] text-white relative overflow-hidden shadow-3xl border border-emerald-500/20">
               <ShieldCheck size={120} className="absolute -bottom-10 -right-10 opacity-10 group-hover:rotate-12 transition-transform duration-1000" />
               <h3 className="text-2xl font-black mb-4 uppercase tracking-tighter italic">Vault Secure</h3>
               <p className="text-emerald-100 font-medium text-sm leading-relaxed">
                  Search directives are generated strictly via local client logic. No domain configuration telemetry is authorized for cloud transmission.
               </p>
            </div>
          </div>
        </div>

        {/* ══════════════════════════════════════════
            DOCUMENTATION & FAQ
        ══════════════════════════════════════════ */}
        <div className="mt-40 border-t border-slate-800 pt-40">
          <div className="grid lg:grid-cols-2 gap-24 items-start">
            <div className="space-y-16">
              <div className="flex items-center gap-4">
                <div className="w-16 h-16 bg-emerald-500/10 rounded-[1.5rem] flex items-center justify-center text-emerald-400 border border-emerald-500/20">
                  <HelpCircle size={32} />
                </div>
                <div>
                  <h2 className="text-4xl font-black text-white uppercase tracking-tight leading-none italic">Shield <span className="text-emerald-400">FAQ</span></h2>
                  <p className="text-slate-500 font-bold text-[10px] uppercase tracking-widest mt-2">Compliance Queries</p>
                </div>
              </div>

              <div className="space-y-6">
                {[
                  { q: "Where does the file go?", a: "The robots.txt file must reside in your domain's root directory (e.g., domain.com/robots.txt). Subdirectory placement results in index failure." },
                  { q: "Does this block all scrapers?", a: "Negative. Robots.txt is a polite directive. Malicious actors may ignore these rules, but major engines (Google, Bing) adhere to them." },
                  { q: "Why block AI scrapers?", a: "AI bots (e.g., GPTBot) index content for model training. Blocking them preserves intellectual property and reduces server overhead." }
                ].map((faq, i) => (
                  <div key={i} className="p-8 bg-white/5 rounded-[2.5rem] border border-white/5 hover:border-emerald-500/20 transition-all group">
                    <h3 className="font-black text-white text-sm mb-4 flex items-start gap-4">
                      <span className="text-emerald-400 font-mono">Q.</span> {faq.q}
                    </h3>
                    <p className="text-slate-400 text-sm leading-relaxed font-medium pl-8 group-hover:text-slate-300 transition-colors">{faq.a}</p>
                  </div>
                ))}
              </div>
            </div>

            <div className="bg-[#0f172a] rounded-[4rem] p-16 md:p-20 text-white relative overflow-hidden border border-white/5">
               <div className="absolute top-0 right-0 w-full h-full opacity-[0.02] pointer-events-none" style={{ backgroundImage: "radial-gradient(#fff 1px, transparent 1px)", backgroundSize: "40px 40px" }} />
               <div className="relative z-10 text-center sm:text-left">
                  <div className="w-24 h-24 bg-emerald-500/10 border border-emerald-500/20 rounded-[2rem] flex items-center justify-center mb-12 shadow-[0_0_80px_rgba(16,185,129,0.2)] mx-auto sm:mx-0">
                    <BookOpen size={48} className="text-emerald-400" />
                  </div>
                  <h3 className="text-4xl font-black mb-8 tracking-tight uppercase leading-none">Best Practices</h3>
                  <p className="text-slate-400 font-medium mb-16 leading-relaxed text-xl">
                    For high-security architectures, explicitly block sensitive 
                    directories like /admin and /wp-admin in the global directive.
                  </p>
                  
                  <div className="grid grid-cols-2 gap-12">
                     <div className="space-y-4">
                        <div className="text-4xl font-black text-white tracking-tighter">SEO+</div>
                        <div className="text-[10px] font-bold text-emerald-400 uppercase tracking-[0.3em]">Compliance Index</div>
                     </div>
                     <div className="space-y-4">
                        <div className="text-4xl font-black text-white tracking-tighter">RFC</div>
                        <div className="text-[10px] font-bold text-emerald-400 uppercase tracking-[0.3em]">Direct Logic</div>
                     </div>
                  </div>
               </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}
