"use client";

import { useState } from "react";
import { Shield, Copy, Check, Info, Settings2, Terminal, AlertCircle, Zap, BookOpen, HelpCircle } from "lucide-react";
import { generateSoftwareApplicationSchema } from "@/lib/structuredData";

export default function RobotsTxtBuilderPage() {
  const [sitemap, setSitemap] = useState("https://yourdomain.com/sitemap.xml");
  const [allowGoogle, setAllowGoogle] = useState(true);
  const [allowBing, setAllowBing] = useState(true);
  const [allowAI, setAllowAI] = useState(false);
  const [disallowAdmin, setDisallowAdmin] = useState(true);
  const [disallowCgi, setDisallowCgi] = useState(true);
  const [delay, setDelay] = useState(0);
  const [copied, setCopied] = useState(false);

  const generateRobots = () => {
    let robots = "# robots.txt generated by SamToolbox Search Engine\n";
    robots += `# Date: ${new Date().toLocaleDateString()}\n\n`;

    if (delay > 0) {
      robots += `User-agent: *\nCrawl-delay: ${delay}\n\n`;
    }

    if (!allowAI) {
      robots += "# Block AI Scrapers\nUser-agent: GPTBot\nDisallow: /\nUser-agent: Claude-Web\nDisallow: /\nUser-agent: CCBot\nDisallow: /\n\n";
    }

    if (!allowGoogle) robots += "User-agent: Googlebot\nDisallow: /\n\n";
    if (!allowBing) robots += "User-agent: Bingbot\nDisallow: /\n\n";

    robots += "User-agent: *\n";
    if (disallowAdmin) robots += "Disallow: /admin/\nDisallow: /login/\nDisallow: /wp-admin/\n";
    if (disallowCgi) robots += "Disallow: /cgi-bin/\nDisallow: /tmp/\n";
    robots += "Allow: /\n\n";

    if (sitemap) {
      robots += `Sitemap: ${sitemap}\n`;
    }

    return robots.trim();
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(generateRobots());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <>
      <div className="max-w-7xl mx-auto py-8 sm:py-12 px-4 sm:px-6 lg:px-8">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(generateSoftwareApplicationSchema("robots-txt-builder", "Industrial-grade search compliance engine for high-security websites.")) }}
      />

      {/* Header */}
      <div className="flex flex-col lg:flex-row items-start lg:items-center justify-between gap-8 mb-12 sm:mb-16">
        <div className="space-y-4">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-emerald-50 text-emerald-700 text-[10px] font-black uppercase tracking-[0.2em] border border-emerald-100">
            <Zap size={12} />
            <span>Search Compliance Protocol</span>
          </div>
          <h1 className="text-4xl sm:text-6xl font-black text-slate-900 tracking-tighter leading-none">
            Crawler <span className="text-emerald-600">Shield</span>
          </h1>
          <p className="text-slate-500 text-sm sm:text-base font-medium max-w-md">
            Control search engine behavior and protect your proprietary data from AI scrapers with precision.
          </p>
        </div>

        <div className="flex items-center gap-4 p-6 bg-slate-50 rounded-3xl border border-slate-100">
           <div className="w-10 h-10 rounded-2xl bg-white flex items-center justify-center text-emerald-500 shadow-sm border border-slate-100">
              <Terminal size={20} />
           </div>
           <div>
              <p className="text-[10px] font-black text-slate-900 uppercase tracking-widest leading-none mb-1">Index Ready</p>
              <p className="text-[9px] font-bold text-slate-400 uppercase tracking-tight">Crawl-Safe v4.0 Verified</p>
           </div>
        </div>
      </div>

      <div className="grid lg:grid-cols-12 gap-12">
        {/* Workspace */}
        <div className="lg:col-span-7 space-y-8">
           <div className="bg-white rounded-[2rem] sm:rounded-[2.5rem] border border-slate-100 shadow-2xl overflow-hidden">
              <div className="bg-slate-50/50 px-6 sm:px-10 py-5 sm:py-6 border-b border-slate-100 flex items-center justify-between">
                <div className="flex items-center gap-3">
                    <div className="w-2 h-2 rounded-full bg-emerald-500" />
                    <span className="text-[10px] font-black text-slate-400 uppercase tracking-widest">Crawler Directives</span>
                </div>
                <div className="flex gap-2">
                    <div className="w-2 h-2 rounded-full bg-slate-200" />
                    <div className="w-2 h-2 rounded-full bg-slate-200" />
                </div>
              </div>

              <div className="p-6 sm:p-10 space-y-8 sm:space-y-10">
                <div>
                  <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-3 block px-1">Sitemap Index URL</label>
                  <input
                    type="url"
                    value={sitemap}
                    onChange={(e) => setSitemap(e.target.value)}
                    placeholder="https://yourdomain.com/sitemap.xml"
                    className="w-full px-5 sm:px-6 py-3 sm:py-4 rounded-xl sm:rounded-2xl bg-slate-50 border-2 border-transparent focus:border-emerald-500/20 focus:bg-white focus:ring-4 focus:ring-emerald-500/5 outline-none transition-all text-sm font-bold text-slate-700"
                  />
                </div>

                <div className="grid sm:grid-cols-2 gap-6 sm:gap-8">
                   <div className="space-y-4">
                      <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest block px-1">Search Engine Bots</label>
                      <div className="space-y-2">
                         {[
                           { label: "Google Search", state: allowGoogle, setState: setAllowGoogle },
                           { label: "Bing / Yahoo", state: allowBing, setState: setAllowBing },
                         ].map((bot, i) => (
                           <button
                             key={i}
                             onClick={() => bot.setState(!bot.state)}
                             className={`w-full flex items-center justify-between p-3.5 sm:p-4 rounded-xl border transition-all ${bot.state ? "bg-emerald-50 border-emerald-100 text-emerald-900" : "bg-slate-50 border-slate-100 text-slate-400"}`}
                           >
                             <span className="text-xs font-black uppercase tracking-tight">{bot.label}</span>
                             <div className={`w-2 h-2 rounded-full ${bot.state ? "bg-emerald-500 shadow-[0_0_8px_rgba(16,185,129,0.5)]" : "bg-slate-300"}`} />
                           </button>
                         ))}
                      </div>
                   </div>

                   <div className="space-y-4">
                      <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest block px-1">Security Filters</label>
                      <div className="space-y-2">
                         {[
                           { label: "Protect Admin Paths", state: disallowAdmin, setState: setDisallowAdmin },
                           { label: "Block AI Scrapers", state: !allowAI, setState: () => setAllowAI(!allowAI) },
                         ].map((rule, i) => (
                           <button
                             key={i}
                             onClick={rule.setState}
                             className={`w-full flex items-center justify-between p-3.5 sm:p-4 rounded-xl border transition-all ${rule.state ? "bg-slate-900 border-slate-800 text-white" : "bg-slate-50 border-slate-100 text-slate-400"}`}
                           >
                             <span className="text-xs font-black uppercase tracking-tight">{rule.label}</span>
                             <div className={`w-2 h-2 rounded-full ${rule.state ? "bg-emerald-400" : "bg-slate-300"}`} />
                           </button>
                         ))}
                      </div>
                   </div>
                </div>

                <div>
                  <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-3 block px-1">Crawl Speed Delay</label>
                  <div className="flex gap-4 items-center">
                    <input
                      type="range"
                      min="0"
                      max="10"
                      value={delay}
                      onChange={(e) => setDelay(parseInt(e.target.value))}
                      className="flex-1 accent-emerald-500"
                    />
                    <span className="text-base sm:text-lg font-black text-slate-900 w-10 sm:w-12">{delay}s</span>
                  </div>
                </div>
              </div>
           </div>
        </div>

        {/* Output */}
        <div className="lg:col-span-5 space-y-8">
           <div className="bg-[#0f172a] rounded-[2rem] sm:rounded-[2.5rem] shadow-2xl p-6 sm:p-10 relative overflow-hidden group">
              <div className="absolute top-0 right-0 -mr-10 -mt-10 w-40 h-40 bg-emerald-500 rounded-full blur-[80px] opacity-20" />
              
              <div className="relative flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 mb-8">
                 <h3 className="text-sm font-black text-white uppercase tracking-widest flex items-center gap-3">
                    <Terminal size={18} className="text-emerald-400" />
                    Terminal Output
                 </h3>
                 <button
                   onClick={handleCopy}
                   className={`w-full sm:w-auto px-6 py-2.5 rounded-xl text-[10px] font-black uppercase tracking-widest transition-all flex items-center justify-center gap-2 ${copied ? "bg-emerald-500 text-white" : "bg-white/10 text-white hover:bg-white/20"}`}
                 >
                   {copied ? <Check size={14} /> : <Copy size={14} />}
                   {copied ? "COPIED" : "COPY CONTENT"}
                 </button>
              </div>

              <div className="bg-slate-900/50 rounded-2xl p-6 sm:p-8 border border-white/5 font-mono text-[11px] sm:text-[13px] text-emerald-300/80 leading-relaxed h-[400px] overflow-auto scrollbar-hide whitespace-pre-wrap break-all">
                 {generateRobots()}
              </div>
           </div>

           <div className="bg-amber-600 rounded-[2rem] p-8 text-white shadow-2xl shadow-amber-200">
              <div className="flex items-center gap-3 mb-4">
                <AlertCircle size={18} />
                <span className="text-[10px] font-black uppercase tracking-[0.2em]">Security Warning</span>
              </div>
              <p className="text-xs font-bold text-amber-100 leading-relaxed">
                Blocking major bots like Googlebot can remove your site from search results. Use AI blocking if you want to protect your content from being used in LLM training.
              </p>
           </div>
        </div>
      </div>
    </div>

      {/* Information Section */}
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="mt-20 grid lg:grid-cols-2 gap-12 border-t border-slate-100 pt-16">
          <div className="space-y-8">
            <div className="flex items-center gap-3 mb-2">
              <div className="p-2 bg-emerald-50 rounded-xl text-emerald-600">
                <BookOpen size={20} />
              </div>
              <h2 className="text-2xl font-black text-slate-900 tracking-tight uppercase">Compliance Protocol</h2>
            </div>
            
            <div className="space-y-6">
              {[
                { step: "01", title: "Define Sitemap", desc: "Input your primary XML sitemap URL. This provides search engines with a roadmap of your site's architecture." },
                { step: "02", title: "Bot Logic", desc: "Select which crawlers are authorized. You can explicitly block AI scrapers to protect your proprietary data from LLM training." },
                { step: "03", title: "Apply Filters", desc: "Configure security filters for administrative paths. This signals legitimate crawlers to ignore sensitive internal directories." },
                { step: "04", title: "Export Directives", desc: "Copy the terminal output and save it as a 'robots.txt' file. Upload this file directly to the root of your domain." }
              ].map((item, i) => (
                <div key={i} className="flex gap-6 group">
                  <span className="text-3xl font-black text-slate-100 group-hover:text-emerald-100 transition-colors duration-300">{item.step}</span>
                  <div className="space-y-1">
                    <h3 className="font-black text-slate-800 uppercase tracking-wide text-sm">{item.title}</h3>
                    <p className="text-slate-500 text-sm leading-relaxed">{item.desc}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>

          <div className="space-y-8">
            <div className="flex items-center gap-3 mb-2">
              <div className="p-2 bg-slate-900 rounded-xl text-white">
                <HelpCircle size={20} />
              </div>
              <h2 className="text-2xl font-black text-slate-900 tracking-tight uppercase">Search Intelligence FAQ</h2>
            </div>

            <div className="space-y-4">
              {[
                { q: "Where should the file be uploaded?", a: "The robots.txt file must be placed in the top-level directory of your web server (e.g., yourdomain.com/robots.txt)." },
                { q: "Why block AI scrapers?", a: "Blocking bots like GPTBot or Claude-Web prevents AI companies from indexing your content to train future language models without your consent." },
                { q: "Does this provide security?", a: "No. Robots.txt is a directive for 'good' bots. Malicious crawlers may ignore it. Always use password protection for truly private content." },
                { q: "What is Crawl-delay?", a: "It tells bots to wait a specified number of seconds between requests. This helps prevent your server from being overwhelmed by high-speed crawlers." }
              ].map((faq, i) => (
                <div key={i} className="p-6 bg-slate-50 rounded-2xl border border-slate-100 hover:bg-white hover:shadow-xl hover:shadow-slate-200/50 transition-all duration-300">
                  <h3 className="font-black text-slate-900 text-xs uppercase tracking-widest mb-2 flex items-center gap-2">
                    <span className="w-1.5 h-1.5 rounded-full bg-emerald-500" />
                    {faq.q}
                  </h3>
                  <p className="text-slate-500 text-xs leading-relaxed font-medium">{faq.a}</p>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
